# -*- coding: utf-8 -*-
"""Copy of Last one large.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XV99ff3gu-vvLxTaJVUXMf-lgAL0ElV
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

# Pip install method

!pip install ultralytics

from IPython import display

import ultralytics

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="nxKQmigopMbRMy7u295N")
project = rf.workspace("hust-ajpvu").project("food-srnub")
dataset = project.version(1).download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=segment mode=train model=yolov8l-seg.pt data={dataset.location}/data.yaml epochs=25 imgsz=640

!ls  {HOME}/runs/segment/train/

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/segment/train/results.png',width=800)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/segment/train/labels.jpg',width=800)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/segment/train/confusion_matrix.png',width=800)

Image(filename=f'/content/runs/segment/train/val_batch2_pred.jpg', width=900)

# Commented out IPython magic to ensure Python compatibility.
#validate the model (not neccessary)
# %cd {HOME}
!yolo task=segment mode=val model={HOME}/runs/segment/train/weights/best.pt data={dataset.location}/data.yaml

# Commented out IPython magic to ensure Python compatibility.
#test the model
# %cd {HOME}
!yolo task=segment mode=predict model={HOME}/runs/segment/train/weights/best.pt  conf=0.25 source={dataset.location}/test/images

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'{HOME}/runs/segment/predict/*.jpg')[:20]:
      display(Image(filename=image_path, width=600))
      print("\n")

from google.colab import drive
drive.mount('/content/drive')

!yolo task=segment mode=predict model={HOME}/runs/segment/train/weights/best.pt  conf=0.25 source='/content/drive/MyDrive/Test Pictures'

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'{HOME}/runs/segment/predict2/*.jpg')[:20]:
      display(Image(filename=image_path, width=500))
      print("\n")

project.version(dataset.version).deploy(model_type="yolov8l-seg", model_path=f"/content/runs/segment/train")

!yolo export model=/content/runs/segment/train/weights/best.pt format=onnx